"""Add customer lifecycle fields

Revision ID: ffed4f6af45a
Revises: 3d2ee485fd46
Create Date: 2026-08-14 10:26:52.845425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffed4f6af45a'
down_revision: Union[str, Sequence[str], None] = '3d2ee485fd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'customers',
        sa.Column(
            'name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default=sa.text("'Unnamed'"),
        ),
    )
    op.add_column('customers', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        'customers',
        sa.Column(
            'status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default=sa.text("'active'"),
        ),
    )
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_customers_slug'), 'customers', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_slug'), table_name='customers')
    op.drop_column('customers', 'archived_at')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'slug')
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###
